### ISSUE TITLE
How should asset processing properties be validated?

### ISSUE THREAD

**Issue by l0b0** [stac-extensions/processing#17]
The schema contains the following section:

```json
{
  "type": "object",
  "$comment": "This validates the fields in Collection Assets, but does not require them.",
  "required": [
    "assets"
  ],
  "properties": {
    "assets": {
      "type": "object",
      "not": {
        "additionalProperties": {
          "not": {
            "allOf": [
              {
                "$ref": "#/definitions/require_any_field"
              },
              {
                "$ref": "#/definitions/fields"
              }
            ]
          }
        }
      }
    }
  }
}
```

What is the semantics meant to be? Are the `not`s actually meant to be there? I would expect the idea is that if there are any assets then any processing properties within them should be *valid,* not invalid. In code, I'd expect the following test to pass:

```js
it('should fail validation when asset processing expression is invalid', async () => {
	// given
	example.assets = {
		'example': {
			'href': 'https://example.org/file.xyz',
			'processing:expression': null,
		}
	};

	// when
	let valid = validate(example);

	// then
	expect(valid).toBeFalsy();
	expect(
		validate.errors.some(
			(error) =>
				error.instancePath === '/assets/example/processing:expression'
				&& error.message === 'must be object',
		)
	).toBeTruthy();
});
```

**Comment by m-mohr** [comment]
The weird "not" validation is a workaround for not having an object-based "contains" in JSON Schema draft 7, see https://github.com/json-schema-org/json-schema-spec/issues/1077#issuecomment-782926462 for details. So if you replace the chained "not" "additionalProperties" "not" with a "contains" (in your mind) it may make more sense. I assume this is solved then? Otherwise, let me know.
